# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Whether JavaScript can open new tabs without user interaction.
# Type: Bool
c.content.javascript.can_open_tabs_automatically = True

# Enables or disables plugins in Web pages.
# Type: Bool
c.content.plugins = False

# Search engines
c.url.searchengines = {
    'DEFAULT': "https://duckduckgo.com/?q={}",
    'arch'   : "https://wiki.archlinux.org/index.php?search={}",
    'pac'    : "https://archlinux.org/packages/?q={}",
    'aur'    : "https://aur.archlinux.org/packages/{}",
    'reddit' : "https://reddit.com/search?q={}",
    'sub'    : "https://reddit.com/r/{}",
    'tex'    : "http://texdoc.net/pkg/{}",
    'xmonad' : "https://hackage.haskell.org/package/xmonad-contrib-0.13/docs/{}.html",
    'youtube': "https://youtube.com/resuls?search_query={}"
}
