#! /bin/sh
#
# rice.sh
# Copyright (C) 2017 pavle <pavle.portic@tilda.center>
#
# Distributed under terms of the MIT license.
#

IMAGE_PATH="$1"
[[ "$1" == "" ]] && IMAGE_PATH=$(rewall)

echo $IMAGE_PATH
wal -i $IMAGE_PATH
